version: '3.9'

services:
  nestapp:
    build: ./
    ports: 
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  pgdata:
