import { Product } from "src/products/Products.entity";

export function getInitialProducts(): Product[] {
  return [
    {
      id: '1',
      name: 'Product Uno',
      description: 'Este es el producto 1',
      price: 100,
      stock: 1,
      imgUrl: 'http://example.com/img1',
    },
    {
      id: '2',
      name: 'Producto 2',
      description: 'Este es el producto 2',
      price: 200,
      stock: 0,
      imgUrl: 'https://example.com/img2',
    },
    {
      id: '3',
      name: 'Producto 3',
      description: 'Este es el producto 3',
      price: 150,
      stock: 1,
      imgUrl: 'https://example.com/img3',
    },
    {
      id: '4',
      name: 'Producto 4',
      description: 'Este es el producto 4',
      price: 250,
      stock: 0,
      imgUrl: 'https://example.com/img4',
    },
    {
      id: '5',
      name: 'Producto 5',
      description: 'Este es el producto 5',
      price: 300,
      stock: 1,
      imgUrl: 'https://example.com/img5',
    },
    {
      id: '6',
      name: 'Producto 6',
      description: 'Este es el producto 6',
      price: 350,
      stock: 0,
      imgUrl: 'https://example.com/img6',
    },
    {
      id: '7',
      name: 'Producto 7',
      description: 'Este es el producto 7',
      price: 400,
      stock: 1,
      imgUrl: 'https://example.com/img7',
    },
    {
      id: '8',
      name: 'Producto 8',
      description: 'Este es el producto 8',
      price: 450,
      stock: 0,
      imgUrl: 'https://example.com/img8',
    },
    {
      id: '9',
      name: 'Producto 9',
      description: 'Este es el producto 9',
      price: 500,
      stock: 1,
      imgUrl: 'https://example.com/img9',
    },
    {
      id: '10',
      name: 'Producto 10',
      description: 'Este es el producto 10',
      price: 550,
      stock: 0,
      imgUrl: 'https://example.com/img10',
    },
    {
      id: '11',
      name: 'Producto 11',
      description: 'Este es el producto 11',
      price: 600,
      stock: 1,
      imgUrl: 'https://example.com/img11',
    },
    {
      id: '12',
      name: 'Producto 12',
      description: 'Este es el producto 12',
      price: 650,
      stock: 0,
      imgUrl: 'https://example.com/img12',
    },
    {
      id: '13',
      name: 'Producto 13',
      description: 'Este es el producto 13',
      price: 700,
      stock: 1,
      imgUrl: 'https://example.com/img13',
    },
    {
      id: '14',
      name: 'Producto 14',
      description: 'Este es el producto 14',
      price: 750,
      stock: 0,
      imgUrl: 'https://example.com/img14',
    },
    {
      id: '15',
      name: 'Producto 15',
      description: 'Este es el producto 15',
      price: 800,
      stock: 1,
      imgUrl: 'https://example.com/img15',
    },
    {
      id: '16',
      name: 'Producto 16',
      description: 'Este es el producto 16',
      price: 850,
      stock: 0,
      imgUrl: 'https://example.com/img16',
    },
    {
      id: '17',
      name: 'Producto 17',
      description: 'Este es el producto 17',
      price: 900,
      stock: 1,
      imgUrl: 'https://example.com/img17',
    },
    {
      id: '18',
      name: 'Producto 18',
      description: 'Este es el producto 18',
      price: 950,
      stock: 0,
      imgUrl: 'https://example.com/img18',
    },
    {
      id: '19',
      name: 'Producto 19',
      description: 'Este es el producto 19',
      price: 1000,
      stock: 1,
      imgUrl: 'https://example.com/img19',
    },
    {
      id: '20',
      name: 'Producto 20',
      description: 'Este es el producto 20',
      price: 1050,
      stock: 0,
      imgUrl: 'https://example.com/img20',
    },
    {
      id: '21',
      name: 'Producto 21',
      description: 'Este es el producto 21',
      price: 1100,
      stock: 1,
      imgUrl: 'https://example.com/img21',
    }
  ];
}
