import { User } from '../users/Users.entity'; // Ajusta la ruta si es necesario

export function getInitialUsers(): Partial<User>[] {
  return [
    {
      id: '1',
      email: 'jorge@email.com',
      name: 'Jorge M',
      password: '123456',
      address: 'Corrientes 2020',
      phone: 1134349065,
      country: 'Argentina',
      city: 'CABA',
    },
    {
      id: '2',
      email: 'susana@email.com',
      name: 'Susana V',
      password: 'abcdef',
      address: 'Cordoba 4545',
      phone: 1176549076,
      country: 'Argentina',
      city: 'CABA',
    },
    {
      id: '3',
      email: 'john.doe@email.com',
      name: 'John Doe',
      password: 'password123',
      address: 'Main St 123',
      phone: 1198765432,
      country: 'USA',
      city: 'New York',
    },
    {
      id: '4',
      email: 'jane.smith@email.com',
      name: 'Jane Smith',
      password: 'qwerty',
      address: 'Oak Avenue 456',
      phone: 1187654321,
      country: 'Canada',
      city: 'Toronto',
    },
    {
      id: '5',
      email: 'mike.jones@email.com',
      name: 'Mike Jones',
      password: 'mikepass',
      address: 'Pine Street 789',
      phone: 1165432187,
      country: 'UK',
      city: 'London',
    },
    {
      id: '6',
      email: 'emily.watson@email.com',
      name: 'Emily Watson',
      password: 'emilypass',
      address: 'Birch Avenue 101',
      phone: 1156784321,
      country: 'Australia',
      city: 'Sydney',
    },
    {
      id: '7',
      email: 'daniel.carter@email.com',
      name: 'Daniel Carter',
      password: 'danpass456',
      address: 'River Road 202',
      phone: 1176543219,
      country: 'New Zealand',
      city: 'Auckland',
    },
    {
      id: '8',
      email: 'sophia.turner@email.com',
      name: 'Sophia Turner',
      password: 'sophiapass',
      address: 'Beach Street 303',
      phone: 1145678912,
      country: 'Spain',
      city: 'Barcelona',
    },
    {
      id: '9',
      email: 'lucas.brown@email.com',
      name: 'Lucas Brown',
      password: 'lucaspass123',
      address: 'Maple Street 404',
      phone: 1132456789,
      country: 'Brazil',
      city: 'Rio de Janeiro',
    },
    {
      id: '10',
      email: 'amelia.clark@email.com',
      name: 'Amelia Clark',
      password: 'ameliapass456',
      address: 'Cedar Avenue 505',
      phone: 1156789123,
      country: 'France',
      city: 'Paris',
    },
    {
      id: '11',
      email: 'henry.morris@email.com',
      name: 'Henry Morris',
      password: 'henrypass789',
      address: 'Elm Street 606',
      phone: 1189765432,
      country: 'Germany',
      city: 'Berlin',
    },
    {
      id: '12',
      email: 'isabella.roberts@email.com',
      name: 'Isabella Roberts',
      password: 'isapass321',
      address: 'Willow Avenue 707',
      phone: 1123456789,
      country: 'Italy',
      city: 'Rome',
    }
  ];
}